spring:

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://104.199.132.220:3306/gas0?useUnicode=true&characterEncoding=utf-8&useSSL=false
        sql-script-encoding: utf-8
        username: root
        password: PI7jnuldfLuE

    second-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://104.199.132.220:3306/gas1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        sql-script-encoding: utf-8
        username: root
        password: PI7jnuldfLuE

    three-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://104.199.132.220:3306/gas2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        sql-script-encoding: utf-8
        username: root
        password: PI7jnuldfLuE

    four-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://104.199.132.220:3306/gas3?useUnicode=true&characterEncoding=utf-8&useSSL=false
        sql-script-encoding: utf-8
        username: root
        password: PI7jnuldfLuE

    five-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://104.199.132.220:3306/gas4?useUnicode=true&characterEncoding=utf-8&useSSL=false
        sql-script-encoding: utf-8
        username: root
        password: PI7jnuldfLuE