# Server settings

server:
    name: pay
    port: 8080
    address: 0.0.0.0
    sessionTimeout: 30
    contextPath: /

spring:

    http:
        encoding:
            force: true

    profiles:
        active: dev