# Server settings

server:
    name: pay
    port: 8080
    address: 0.0.0.0
    sessionTimeout: 30
    contextPath: /

spring:

    http:
        encoding:
            force: true

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas0?useUnicode=true&characterEncoding=utf-8&useSSL=true
        sql-script-encoding: utf-8
        username: root
        password: 123456

    second-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas1?useUnicode=true&characterEncoding=utf-8&useSSL=true
        sql-script-encoding: utf-8
        username: root
        password: 123456

    three-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas2?useUnicode=true&characterEncoding=utf-8&useSSL=true
        sql-script-encoding: utf-8
        username: root
        password: 123456

    four-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas3?useUnicode=true&characterEncoding=utf-8&useSSL=true
        sql-script-encoding: utf-8
        username: root
        password: 123456

    five-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas4?useUnicode=true&characterEncoding=utf-8&useSSL=true
        sql-script-encoding: utf-8
        username: root
        password: 123456