spring:

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas0?useUnicode=true&characterEncoding=utf-8
        sql-script-encoding: utf-8
        username: root
        password: mysql

    second-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas1?useUnicode=true&characterEncoding=utf-8
        sql-script-encoding: utf-8
        username: root
        password: mysql

    three-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas2?useUnicode=true&characterEncoding=utf-8
        sql-script-encoding: utf-8
        username: root
        password: mysql

    four-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas3?useUnicode=true&characterEncoding=utf-8
        sql-script-encoding: utf-8
        username: root
        password: mysql

    five-datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/gas4?useUnicode=true&characterEncoding=utf-8
        sql-script-encoding: utf-8
        username: root
        password: mysql