# Server settings

server:
    name: pay
    port: 8080
    address: 0.0.0.0
    sessionTimeout: 30
    contextPath: /


# 配置文档参见 http://t.cn/RVUkLNl
mybatis:
    typeAliasesPackage: cn.demo.gas.pay.model
    configLocation: classpath:mybatis-config.xml
    mapperLocations: classpath:mybatis/*.xml

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/junping
        username: root
        password: 123456